const httpResponse={
    INTERNAL_ERROR:'Internal Error please try later',
    SERVER_ERROR:'Internal Server Error',
    INVALID_DATE_RANGE:'Invalid startDate or endDate',
    MISSING_IMAGE_AND_TITLE:'Please add both an image and a title.',
    NOT_LOGGED_IN:'User is not logged in.',

    INVALID_EMAIL:'InValid Email',
    PASSWORD_NOT_MATCH:'password not match',
    LOGIN_SUCCESS:'Login succesfully',
    VERIFY_FAILED:'failed to verify',
    UPDATED_SUCCESS:'succesfully Updated',
    CATEGORY_EXISTS:'Category Exist with This Title',
    CATEGORY_ADDED:'Category successfully Added',
    CATEGORY_UPDATED:'Category Updated',
    UPDATE_FAILED:'failed to update',
    REMOVED_SUCCESS:'succefuly removed',

    PRODUCT_EXISTS:'Product Exist with This Title',
    PRODUCT_ALREADY_EXISTS:'Product Already Exists',
    PRODUCT_IMAGE_REQUIRED:'Upload at least one image',
    PRODUCT_ADDED:'Product added successfully',
    PRODUCT_NOT_FOUND:'Product not found',
    PRODUCT_UPDATED:'Product updated successfully',
    PRODUCT_UPDATE_FAILED:'Failed to update product',
    RESULT_NOT_RECEIVED:'result not recieved',

    OFFER_ID_REQUIRED:'OfferID is required',
    OFFER_NOT_FOUND:'Offer not found',
    CATEGORY_NOT_FOUND_FOR_OFFER:'Category not found for the given offer',
    CATEGORY_OFFER_REMOVED:'Category offer removed successfully',
    PRODUCT_NOT_FOUND_FOR_OFFER:'Product not found for the given offer',
    PRODUCT_OFFER_REMOVED:'Product offer removed successfully',
    INVALID_OFFER_TARGET:'Invalid offer: No categoryId or productId found',
    CATEGORY_NOT_FOUND:'Category not found',
    CATEGORY_OFFER_EXISTS:'offer for this category already exists',
    PRODUCT_OFFER_EXISTS:'offer for this product already exists',
    OFFER_ADDED:'Offer added successfully',

    STOCK_ADDED:'Stock Added',
    SALES_REPORT_ERROR:'Internal server error',

    ORDER_NOT_FOUND:'Order not found',
    ORDER_STATUS_UPDATED:'Order Status Successfully Updated',
    PRODUCT_NOT_FOUND_IN_ORDER:'Product not found in the order.',
    PRODUCT_MARKED_RETURNED:'Product marked as returned.',
    ORDER_MARKED_RETURNED:'Order marked as returned.',
    PRODUCT_RETURN_REJECTED:'Product return rejected.',
    ORDER_RETURN_REJECTED:'Order return rejected.',
    ORDER_PROCESSING_ERROR:'An error occurred while processing the request.',
    RETURN_HANDLE_ERROR:'Internal server error.',
    WALLET_UPDATE_FAILED:'Failed to update wallet.',

    COUPON_EXIST:'Coupon Exist with THIS CODE',
    COUPON_ADDED:'Coupon Added Succesfully',
    INVALID_COUPON:"Invalid Coupon Code",
    Coupon_not_active:"Coupon is not active",
    COUPON_DATE_INVALID:'This coupon is expired or not active yet.',
    COUPON_MAX_REDEEMED:'This coupon has been fully redeemed.',
    COUPON_USER_MAX_USED:'You have already used this coupon the maximum allowed times.',
    COUPON_APPLIED:'Coupon applied successfully!',
    USER_NOT_FOUND:'User not found.',
    CART_NOT_FOUND:'Cart not found.',
    USER_NOT_FOUND_CAP:'User Not Found',
    COUPON_HISTORY_NOT_FOUND:'Coupon not found in user history.',
    CART_NOT_FOUND_DOT:'Cart not found.',
    COUPON_REMOVED:'Coupon removed successfully. Discount has been reset.',

    ADDRESS_EXISTS:'the Address Already Exist',
    ADDRESS_ADDED:'Address succesfully Added',
    ADDRESS_ADD_FAILED:'Failed to add Address',
    ADDRESS_ID_REQUIRED:'Address ID is required',
    ADDRESS_DELETE_FAILED:'Failed to Delete Address',
    ADDRESS_DELETED:'Address Successfully Deleted',
    ADDRESS_UPDATED:'Address Updated Succesfully',

    SOMETHING_WENT_WRONG:'Something went wrong',
    USER_NOT_LOGGED_IN:'User not logged in',
    USER_NOT_LOGGED_IN_CAP:'User is Not Logged In',
    PRODUCT_ADDED_WISHLIST:'Product successfully added to wishlist',
    PRODUCT_REMOVED_WISHLIST:'Product successfully removed from wishlist',
    PRODUCT_REMOVED_WISHLIST_ALT:'Product removed from wishlist',
    PRODUCT_NOT_FOUND_WISHLIST:'Product Not Found in Wishlist',

    PROFILE_UPDATED:'Profile Succesfully Updated',
    PROFILE_UPDATE_FAILED:'failed to update Profile',
    CURRENT_PASSWORD_INVALID:'Current Password is not Match',
    PASSWORD_CHANGED:'Password Successfully Changed',
    PASSWORD_CHANGE_FAILED:'Password change failed',
    RESET_EMAIL_SENT:'Reset email sent',
    RESET_EMAIL_FAILED:'Failed to send reset email',
    INVALID_TOKEN:'Invalid token',
    PASSWORD_UPDATED:'Password updated succesfully',

    CART_FETCH_FAILED:'Error fetching cart',
    CART_UPDATED:'Cart updated successfully',
    PRODUCT_ALREADY_IN_CART:'This product is already in your cart.',
    CART_NOT_FOUND_CAP:'Cart Not Found',
    PRODUCT_NOT_FOUND_IN_CART:'Product Not Found in Cart',
    PRODUCT_NOT_FOUND_IN_DB:'Product Not Found in Database',
    PRODUCT_REMOVED_FROM_CART:'Product removed from cart',
    PRODUCT_NOT_FOUND_IN_CART_LC:'Product not found in cart',
    CART_EMPTY:'Your Cart is Empty',
    CART_EMPTY_API:'Cart is Empty',

    OTP_NOT_FOUND_SESSION:'OTP not found in session.',
    OTP_RESENT:'OTP resent successfully',
    OTP_RESEND_FAILED:'Failed to resend OTP',
    OTP_OR_EMAIL_NOT_FOUND:'OTP or Email not found.',
    OTP_SESSION_NOT_FOUND:'No OTP session data found.',
    OTP_EXPIRED:'OTP Expired!',
    USER_ALREADY_EXISTS:'User already exists.',
    USER_REGISTERED:'User registered successfully.',
    INVALID_OTP_OR_EMAIL:'Invalid OTP or Email',
    INVALID_EMAIL_SMALL:'invalid Email',
    LOGIN_WITH_GOOGLE:'user loged with google, please login with google',
    USER_BLOCKED:'you have been blocked for some reason',
    PASSWORD_NOT_MATCH_USER:'Password not Match',
    USER_LOGIN_SUCCESS:'User Login successfully.',
    NO_PRODUCTS_FOUND:'No products found.',
    PRODUCTS_FETCHED:'Products fetched successfully.',
    PRODUCTS_FETCH_ERROR:'An error occurred while fetching products.',

    ORDER_PLACED:'Order Placed Successfully',
    INVALID_AMOUNT:'Invalid amount',
    MISSING_REQUIRED_FIELDS:'Missing required fields',
    PAYMENT_VERIFIED:'Payment verified successfully',
    INVALID_PAYMENT_SIGNATURE:'Invalid payment signature',
    ORDER_ID_REQUIRED:'Order ID is required',
    RAZORPAY_ORDER_CREATE_FAILED:'Failed to create Razorpay order',
    WALLET_NOT_FOUND:'Wallet Not found',
    INSUFFICIENT_WALLET_BALANCE:'Insufficient Wallet Balance',
    SERVER_ERROR_SHORT:'Server error',

    ORDER_CANCELLED:'Order cancelled',
    ORDER_NOT_FOUND_CAP:'Order not Found',
    RETURN_TIME_EXCEEDED_2DAYS:'Your return time for this order has exceeded 2 days , which the allowed period.',
    RETURN_REQUEST_UPDATED_SOON:'Your Request Updated Soon',
    PRODUCT_RETURN_IMAGE_REQUIRED:'Product image is required.',
    ORDER_NOT_FOUND_DOT:'Order not found.',
    RETURN_TIME_EXCEEDED:'Your return time for this order has exceeded the allowed period.',
    RETURN_REQUEST_UPDATED:'Your request has been updated. We will process it soon.',
    TRY_AGAIN_ERROR:'An error occurred. Please try again.',

    ITEM_NOT_FOUND:(item)=>`${item} not found`,
    UPDATED_SUCCESSFULLY:(item,action)=>`${item} Successfully ${action}`,
    LIST_STATUS_UPDATED:(status)=>`succesfully ${status}`,
    PRODUCT_STATUS_UPDATED:(status)=>`Product successfully ${status.toLowerCase()}.`,
    MIN_CART_VALUE_REQUIRED:(min)=>`Minimum cart value must be at least ${min}.`

}

module.exports = httpResponse
