const httpResponse={
    INTERNAL_ERROR:'Internal Error please try later',
    SERVER_ERROR:'Internal Server Error',
    INVALID_DATE_RANGE:'Invalid startDate or endDate',
    MISSING_IMAGE_AND_TITLE:'Please add both an image and a title.',
    NOT_LOGGED_IN:'User is not logged in.',

    INVALID_EMAIL:'InValid Email',
    PASSWORD_NOT_MATCH:'password not match',
    LOGIN_SUCCESS:'Login succesfully',
    VERIFY_FAILED:'failed to verify',
    UPDATED_SUCCESS:'succesfully Updated',
    CATEGORY_EXISTS:'Category Exist with This Title',
    CATEGORY_ADDED:'Category successfully Added',
    CATEGORY_UPDATED:'Category Updated',
    UPDATE_FAILED:'failed to update',
    REMOVED_SUCCESS:'succefuly removed',

    PRODUCT_EXISTS:'Product Exist with This Title',
    PRODUCT_ALREADY_EXISTS:'Product Already Exists',
    PRODUCT_IMAGE_REQUIRED:'Upload at least one image',
    PRODUCT_ADDED:'Product added successfully',
    PRODUCT_NOT_FOUND:'Product not found',
    PRODUCT_UPDATED:'Product updated successfully',
    PRODUCT_UPDATE_FAILED:'Failed to update product',
    RESULT_NOT_RECEIVED:'result not recieved',

    OFFER_ID_REQUIRED:'OfferID is required',
    OFFER_NOT_FOUND:'Offer not found',
    CATEGORY_NOT_FOUND_FOR_OFFER:'Category not found for the given offer',
    CATEGORY_OFFER_REMOVED:'Category offer removed successfully',
    PRODUCT_NOT_FOUND_FOR_OFFER:'Product not found for the given offer',
    PRODUCT_OFFER_REMOVED:'Product offer removed successfully',
    INVALID_OFFER_TARGET:'Invalid offer: No categoryId or productId found',
    CATEGORY_NOT_FOUND:'Category not found',
    CATEGORY_OFFER_EXISTS:'offer for this category already exists',
    PRODUCT_OFFER_EXISTS:'offer for this product already exists',
    OFFER_ADDED:'Offer added successfully',

    STOCK_ADDED:'Stock Added',
    SALES_REPORT_ERROR:'Internal server error',

    ORDER_NOT_FOUND:'Order not found',
    ORDER_STATUS_UPDATED:'Order Status Successfully Updated',
    PRODUCT_NOT_FOUND_IN_ORDER:'Product not found in the order.',
    PRODUCT_MARKED_RETURNED:'Product marked as returned.',
    ORDER_MARKED_RETURNED:'Order marked as returned.',
    PRODUCT_RETURN_REJECTED:'Product return rejected.',
    ORDER_RETURN_REJECTED:'Order return rejected.',
    ORDER_PROCESSING_ERROR:'An error occurred while processing the request.',
    RETURN_HANDLE_ERROR:'Internal server error.',
    WALLET_UPDATE_FAILED:'Failed to update wallet.',

    COUPON_EXIST:'Coupon Exist with THIS CODE',
    COUPON_ADDED:'Coupon Added Succesfully',
    INVALID_COUPON:"Invalid Coupon Code",
    Coupon_not_active:"Coupon is not active",
    COUPON_DATE_INVALID:'This coupon is expired or not active yet.',
    COUPON_MAX_REDEEMED:'This coupon has been fully redeemed.',
    COUPON_USER_MAX_USED:'You have already used this coupon the maximum allowed times.',
    COUPON_APPLIED:'Coupon applied successfully!',
    USER_NOT_FOUND:'User not found.',
    CART_NOT_FOUND:'Cart not found.',
    USER_NOT_FOUND_CAP:'User Not Found',
    COUPON_HISTORY_NOT_FOUND:'Coupon not found in user history.',
    CART_NOT_FOUND_DOT:'Cart not found.',
    COUPON_REMOVED:'Coupon removed successfully. Discount has been reset.',

    ITEM_NOT_FOUND:(item)=>`${item} not found`,
    UPDATED_SUCCESSFULLY:(item,action)=>`${item} Successfully ${action}`,
    LIST_STATUS_UPDATED:(status)=>`succesfully ${status}`,
    PRODUCT_STATUS_UPDATED:(status)=>`Product successfully ${status.toLowerCase()}.`,
    MIN_CART_VALUE_REQUIRED:(min)=>`Minimum cart value must be at least ${min}.`

}

module.exports = httpResponse
